2021 32x hacks
frederic-mahe/Hardware-Target-Game-Database pull request #729
Opened 2021-12-13 20:36 UTC by blinard-BIOINFO

This PR does the following:

Spotted by @hotelvictorcharlie , in #720 :
- corrects some rom name spelling mistakes
- corrects 2 entries : checksum of Doom 32X Delta Edition Episode 1 and 3 (episode 2 unchanged). They now all match the most recent romhacking.net patch and not the older version from doomworld. 

Doom 32X Hacks updates :
- adds 4 new 'Doom 32X hacks' entries, all patches come from romhacking.net :  
  - Doom 32X Delta Edition episode 4 
  - Doom 32X Delta Edition episode 5
  - European region patch variant for 'Ultimate Doom All Episodes'
  - European region patch variant for 'Doom 2 All Levels Hack Maps'
- updates Doom 32X Resurrection from hack v1.3 to v1.4 (splitscreen coop added !!!)

2021-12-13 23:29 UTC, hotelvictorcharlie requested changes

2021-12-13 23:29 UTC, hotelvictorcharlie commented on EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
> +f1deadad3f7ad6115dfb35147cf1b98dca29c0073e4f6c29cf11be4559782b2b	Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Doom 32X Hacks/Doom 32X - Delta Edition - Episode 1 (Japan, USA) (Hack) v1.0 Roeblez.32x
Should be spelled [Roebloz](https://www.doomworld.com/profile/30346-roebloz/), not Roeblez.

2021-12-17 10:40 UTC, frederic-mahe commented on EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
> +40fc27d6e6cef3434902e17ac518b9ed932ff046b947477a9b158d5c6091b775	Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Doom 32X Hacks/Doom 32X Resurrection (Europe, Japan, USA) (Hack) v1.4 D32XR Team.32x	9a7b
https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/721#issuecomment-995991739

 @Infinitum8t says that there is now a v1.5 of _Doom 32X Resurrection_.

2021-12-17 10:56 UTC, blinard-BIOINFO commented
Indeed a hack update has been released a few days just after this new PR.  XD
I push the update this week-end.

2021-12-17 10:57 UTC, blinard-BIOINFO commented on EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
> +f1deadad3f7ad6115dfb35147cf1b98dca29c0073e4f6c29cf11be4559782b2b	Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Doom 32X Hacks/Doom 32X - Delta Edition - Episode 1 (Japan, USA) (Hack) v1.0 Roeblez.32x
Thanks. I will push the fix this week-end.

2021-12-17 10:57 UTC, blinard-BIOINFO commented on EverDrive Pack SMDBs/Mega EverDrive SMDB.txt
> +40fc27d6e6cef3434902e17ac518b9ed932ff046b947477a9b158d5c6091b775	Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Doom 32X Hacks/Doom 32X Resurrection (Europe, Japan, USA) (Hack) v1.4 D32XR Team.32x	9a7b
Indeed a hack update has been released a few days just after this new PR. XD
I push the update this week-end.

2021-12-17 10:57 UTC, frederic-mahe commented
Thanks @blinard-BIOINFO sorry you have to go through so many hoops.

2021-12-17 11:02 UTC, blinard-BIOINFO commented
> so many hoops
No worries, I'm happy to do these minor contributions to this huge database.

2021-12-18 17:55 UTC, blinard-BIOINFO commented
@frederic-mahe 
the last commit answers @hotelvictorcharlie + @infinitum8t comments

2021-12-18 22:09 UTC, hotelvictorcharlie approved these changes

2021-12-20 09:36 UTC, merged